// Code generated by mockery v2.42.1. DO NOT EDIT.

package authorization

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockCheckerFunc is an autogenerated mock type for the CheckerFunc type
type MockCheckerFunc struct {
	mock.Mock
}

type MockCheckerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckerFunc) EXPECT() *MockCheckerFunc_Expecter {
	return &MockCheckerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r
func (_m *MockCheckerFunc) Execute(r *http.Request) bool {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*http.Request) bool); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCheckerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCheckerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockCheckerFunc_Expecter) Execute(r interface{}) *MockCheckerFunc_Execute_Call {
	return &MockCheckerFunc_Execute_Call{Call: _e.mock.On("Execute", r)}
}

func (_c *MockCheckerFunc_Execute_Call) Run(run func(r *http.Request)) *MockCheckerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockCheckerFunc_Execute_Call) Return(_a0 bool) *MockCheckerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCheckerFunc_Execute_Call) RunAndReturn(run func(*http.Request) bool) *MockCheckerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckerFunc creates a new instance of MockCheckerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckerFunc {
	mock := &MockCheckerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
