// Code generated by mockery v2.42.1. DO NOT EDIT.

package authentication

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// mockMiddlewareHandler is an autogenerated mock type for the middlewareHandler type
type mockMiddlewareHandler struct {
	mock.Mock
}

type mockMiddlewareHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMiddlewareHandler) EXPECT() *mockMiddlewareHandler_Expecter {
	return &mockMiddlewareHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: h
func (_m *mockMiddlewareHandler) Handle(h http.Handler) http.Handler {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// mockMiddlewareHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockMiddlewareHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - h http.Handler
func (_e *mockMiddlewareHandler_Expecter) Handle(h interface{}) *mockMiddlewareHandler_Handle_Call {
	return &mockMiddlewareHandler_Handle_Call{Call: _e.mock.On("Handle", h)}
}

func (_c *mockMiddlewareHandler_Handle_Call) Run(run func(h http.Handler)) *mockMiddlewareHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *mockMiddlewareHandler_Handle_Call) Return(_a0 http.Handler) *mockMiddlewareHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMiddlewareHandler_Handle_Call) RunAndReturn(run func(http.Handler) http.Handler) *mockMiddlewareHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMiddlewareHandler creates a new instance of mockMiddlewareHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMiddlewareHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMiddlewareHandler {
	mock := &mockMiddlewareHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
