// Code generated by mockery v2.42.1. DO NOT EDIT.

package authentication

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockIsAuthenticated is an autogenerated mock type for the IsAuthenticated type
type MockIsAuthenticated struct {
	mock.Mock
}

type MockIsAuthenticated_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIsAuthenticated) EXPECT() *MockIsAuthenticated_Expecter {
	return &MockIsAuthenticated_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: w, r
func (_m *MockIsAuthenticated) Execute(w http.ResponseWriter, r *http.Request) bool {
	ret := _m.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) bool); ok {
		r0 = rf(w, r)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIsAuthenticated_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIsAuthenticated_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockIsAuthenticated_Expecter) Execute(w interface{}, r interface{}) *MockIsAuthenticated_Execute_Call {
	return &MockIsAuthenticated_Execute_Call{Call: _e.mock.On("Execute", w, r)}
}

func (_c *MockIsAuthenticated_Execute_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockIsAuthenticated_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockIsAuthenticated_Execute_Call) Return(_a0 bool) *MockIsAuthenticated_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIsAuthenticated_Execute_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request) bool) *MockIsAuthenticated_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIsAuthenticated creates a new instance of MockIsAuthenticated. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIsAuthenticated(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIsAuthenticated {
	mock := &MockIsAuthenticated{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
