// Code generated by mockery v2.42.1. DO NOT EDIT.

package authentication

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockRedirectToLogout is an autogenerated mock type for the RedirectToLogout type
type MockRedirectToLogout struct {
	mock.Mock
}

type MockRedirectToLogout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedirectToLogout) EXPECT() *MockRedirectToLogout_Expecter {
	return &MockRedirectToLogout_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: w, r
func (_m *MockRedirectToLogout) Execute(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockRedirectToLogout_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRedirectToLogout_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRedirectToLogout_Expecter) Execute(w interface{}, r interface{}) *MockRedirectToLogout_Execute_Call {
	return &MockRedirectToLogout_Execute_Call{Call: _e.mock.On("Execute", w, r)}
}

func (_c *MockRedirectToLogout_Execute_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRedirectToLogout_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockRedirectToLogout_Execute_Call) Return() *MockRedirectToLogout_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRedirectToLogout_Execute_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockRedirectToLogout_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedirectToLogout creates a new instance of MockRedirectToLogout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedirectToLogout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedirectToLogout {
	mock := &MockRedirectToLogout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
