// Code generated by mockery v2.42.1. DO NOT EDIT.

package authentication

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockUsername is an autogenerated mock type for the Username type
type MockUsername struct {
	mock.Mock
}

type MockUsername_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsername) EXPECT() *MockUsername_Expecter {
	return &MockUsername_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r
func (_m *MockUsername) Execute(r *http.Request) string {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUsername_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUsername_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockUsername_Expecter) Execute(r interface{}) *MockUsername_Execute_Call {
	return &MockUsername_Execute_Call{Call: _e.mock.On("Execute", r)}
}

func (_c *MockUsername_Execute_Call) Run(run func(r *http.Request)) *MockUsername_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockUsername_Execute_Call) Return(_a0 string) *MockUsername_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsername_Execute_Call) RunAndReturn(run func(*http.Request) string) *MockUsername_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsername creates a new instance of MockUsername. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsername(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsername {
	mock := &MockUsername{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
