// Code generated by mockery v2.42.1. DO NOT EDIT.

package authentication

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockIsFirstAuthenticatedRequest is an autogenerated mock type for the IsFirstAuthenticatedRequest type
type MockIsFirstAuthenticatedRequest struct {
	mock.Mock
}

type MockIsFirstAuthenticatedRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIsFirstAuthenticatedRequest) EXPECT() *MockIsFirstAuthenticatedRequest_Expecter {
	return &MockIsFirstAuthenticatedRequest_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r
func (_m *MockIsFirstAuthenticatedRequest) Execute(r *http.Request) bool {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*http.Request) bool); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIsFirstAuthenticatedRequest_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIsFirstAuthenticatedRequest_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockIsFirstAuthenticatedRequest_Expecter) Execute(r interface{}) *MockIsFirstAuthenticatedRequest_Execute_Call {
	return &MockIsFirstAuthenticatedRequest_Execute_Call{Call: _e.mock.On("Execute", r)}
}

func (_c *MockIsFirstAuthenticatedRequest_Execute_Call) Run(run func(r *http.Request)) *MockIsFirstAuthenticatedRequest_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockIsFirstAuthenticatedRequest_Execute_Call) Return(_a0 bool) *MockIsFirstAuthenticatedRequest_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIsFirstAuthenticatedRequest_Execute_Call) RunAndReturn(run func(*http.Request) bool) *MockIsFirstAuthenticatedRequest_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIsFirstAuthenticatedRequest creates a new instance of MockIsFirstAuthenticatedRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIsFirstAuthenticatedRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIsFirstAuthenticatedRequest {
	mock := &MockIsFirstAuthenticatedRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
